version: "3.9"
services:
  database:
    image: 'mongo:4.2.21'
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-volume:/data/db
    env_file: .env
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8999:8000"
volumes:
  mongo-volume:
