version: "3.9"
services:
  redis:
    image: "redis:alpine"
    hostname: redis
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8999:8000"
