version: "3.9"
services:
  database:
    image: 'mongo:4.2.21'
    volumes:
      - mongo-volume:/data/db
    env_file: .env
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8999:8000"
  ibm_ssd_model:
    image: 'quay.io/codait/max-object-detector'
volumes:
  mongo-volume:
